require("dotenv").config();
const express=require("express"); const cors=require("cors"); const mongoose=require("mongoose"); const jwt=require("jsonwebtoken");
const Razorpay=require("razorpay"); const {Resend}=require("resend");
const app=express(); app.use(cors()); app.use(express.json());
let dbReady=false;
async function db(){if(dbReady)return; if(!process.env.MONGODB_URI) return; await mongoose.connect(process.env.MONGODB_URI); dbReady=true;}
const Product=mongoose.models.Product||mongoose.model("Product",new mongoose.Schema({name:String,slug:{type:String,unique:true},description:String,price:Number,compareAt:Number,image:String,category:String,stock:{type:Number,default:0},featured:Boolean},{timestamps:true}));
const User=mongoose.models.User||mongoose.model("User",new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,default:"customer"}},{timestamps:true}));
const Order=mongoose.models.Order||mongoose.model("Order",new mongoose.Schema({userId:String,items:Array,total:Number,status:{type:String,default:"pending"},paymentStatus:{type:String,default:"pending"},paymentMethod:String,shipping:Object},{timestamps:true}));
const seed=[["HP Pavilion 15","hp-pavilion-15",54999,"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80","Laptops"],["Logitech MX Master 3S","mx-master-3s",7499,"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80","Accessories"],["Mechanical Keyboard","mechanical-keyboard",3999,"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80","Accessories"],["24-inch FHD Monitor","fhd-monitor",11999,"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80","Monitors"]];
async function seedDb(){await db(); if(!dbReady)return; if(await Product.countDocuments()===0) await Product.insertMany(seed.map(x=>({name:x[0],slug:x[1],price:x[2],image:x[3],category:x[4],description:"Premium product from Deepak Digital Computer Studio.",stock:25,featured:true})));}

app.get("/api/health",async(_,res)=>{try{await db();res.json({status:"ok",service:"Deepak Digital Commerce API",database:dbReady?"connected":"not-configured"})}catch(e){res.status(500).json({status:"error",message:e.message})}});
app.get("/api/products",async(req,res)=>{try{await seedDb(); const q=req.query.q; const filter=q?{$or:[{name:new RegExp(q,"i")},{category:new RegExp(q,"i")}]}:{}; res.json(await Product.find(filter).sort({createdAt:-1}))}catch(e){res.status(500).json({message:e.message})}});
app.get("/api/products/:slug",async(req,res)=>{try{await seedDb(); const p=await Product.findOne({slug:req.params.slug}); if(!p)return res.status(404).json({message:"Product not found"});res.json(p)}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/auth/register",async(req,res)=>{try{await db();const {name,email,password}=req.body;if(!email||!password)return res.status(400).json({message:"Name, email and password required"});let u=await User.findOne({email});if(u)return res.status(409).json({message:"Email already registered"});u=await User.create({name,email,password});res.json({token:jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET||"dev-secret"),user:{name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{await db();const u=await User.findOne({email:req.body.email,password:req.body.password});if(!u)return res.status(401).json({message:"Invalid credentials"});res.json({token:jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET||"dev-secret"),user:{name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/orders",async(req,res)=>{try{await db();const {items,total,paymentMethod="cod",shipping}=req.body;const order=await Order.create({items,total,paymentMethod,shipping,paymentStatus:paymentMethod==="cod"?"pending":"created"}); if(process.env.RESEND_API_KEY) await sendEmail(shipping?.email,"Order received","Your order "+order._id+" has been received.");res.status(201).json(order)}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/payments/create-order",async(req,res)=>{try{if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.json({demo:true,orderId:"demo_"+Date.now()});const rzp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const order=await rzp.orders.create({amount:Math.round(Number(req.body.amount)*100),currency:"INR",receipt:"ddcs_"+Date.now()});res.json({demo:false,keyId:process.env.RAZORPAY_KEY_ID,...order})}catch(e){res.status(500).json({message:e.message})}});
async function sendEmail(to,subject,html){if(!process.env.RESEND_API_KEY||!to)return;const resend=new Resend(process.env.RESEND_API_KEY);await resend.emails.send({from:process.env.FROM_EMAIL||"orders@example.com",to,subject,html})}
app.post("/api/automation/order-confirmation",async(req,res)=>{try{await sendEmail(req.body.to,"Order confirmation",req.body.html||"Thanks for your order!");res.json({sent:Boolean(process.env.RESEND_API_KEY),channel:"email"})}catch(e){res.status(500).json({message:e.message})}});
module.exports=app;