require("dotenv").config();
const express=require("express"),cors=require("cors"),helmet=require("helmet"),mongoose=require("mongoose"),jwt=require("jsonwebtoken"),crypto=require("crypto");
const bcrypt=require("bcryptjs"),Razorpay=require("razorpay"),{Resend}=require("resend");
const app=express();app.use(helmet());app.use(cors({origin:process.env.CLIENT_URL||true}));app.use(express.json({limit:"1mb"}));
let dbReady=false;async function db(){if(dbReady)return;if(!process.env.MONGODB_URI)throw new Error("MONGODB_URI is not configured");await mongoose.connect(process.env.MONGODB_URI);dbReady=true}
const Product=mongoose.models.Product||mongoose.model("Product",new mongoose.Schema({name:{type:String,required:true},slug:{type:String,unique:true,index:true},description:String,price:{type:Number,min:0},compareAt:{type:Number,min:0},image:String,category:{type:String,index:true},stock:{type:Number,default:0,min:0},featured:Boolean,active:{type:Boolean,default:true}},{timestamps:true}));
const User=mongoose.models.User||mongoose.model("User",new mongoose.Schema({name:{type:String,required:true},email:{type:String,unique:true,index:true},passwordHash:String,role:{type:String,enum:["customer","admin"],default:"customer"}},{timestamps:true}));
const Order=mongoose.models.Order||mongoose.model("Order",new mongoose.Schema({userId:String,items:[{productId:String,name:String,price:Number,qty:Number}],total:Number,status:{type:String,enum:["pending","confirmed","processing","shipped","delivered","cancelled"],default:"pending"},paymentStatus:{type:String,enum:["pending","created","paid","failed","refunded"],default:"pending"},paymentMethod:String,paymentOrderId:String,paymentId:String,shipping:Object},{timestamps:true}));
const Coupon=mongoose.models.Coupon||mongoose.model("Coupon",new mongoose.Schema({code:{type:String,unique:true,index:true},type:{type:String,enum:["percent","fixed"]},value:Number,minOrder:{type:Number,default:0},active:{type:Boolean,default:true},expiresAt:Date}));
const seed=[["HP Pavilion 15","hp-pavilion-15",54999,"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80","Laptops"],["Logitech MX Master 3S","mx-master-3s",7499,"https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80","Accessories"],["Mechanical Keyboard","mechanical-keyboard",3999,"https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80","Accessories"],["24-inch FHD Monitor","fhd-monitor",11999,"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80","Monitors"]];
async function seedDb(){await db();if(await Product.countDocuments()===0)await Product.insertMany(seed.map(x=>({name:x[0],slug:x[1],price:x[2],image:x[3],category:x[4],description:"Premium product from Deepak Digital Computer Studio.",stock:25,featured:true})))}
function token(u){return jwt.sign({id:u._id.toString(),role:u.role},process.env.JWT_SECRET||"dev-secret",{expiresIn:"7d"})}
function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({message:"Authentication required"});req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET||"dev-secret");next()}catch{return res.status(401).json({message:"Invalid or expired token"})}}
function admin(req,res,next){return req.user?.role==="admin"?next():res.status(403).json({message:"Admin access required"})}
async function sendEmail(to,subject,html){if(!process.env.RESEND_API_KEY||!to)return{sent:false};const resend=new Resend(process.env.RESEND_API_KEY);await resend.emails.send({from:process.env.FROM_EMAIL||"orders@example.com",to,subject,html});return{sent:true}}
app.get("/api/health",async(_,res)=>{try{await db();res.json({status:"ok",service:"Deepak Digital Commerce API",database:"connected"})}catch(e){res.status(500).json({status:"error",message:e.message})}});
app.get("/api/products",async(req,res)=>{try{await seedDb();const q=String(req.query.q||""),cat=String(req.query.category||"");const filter={active:true,...(q?{$or:[{name:new RegExp(q,"i")},{category:new RegExp(q,"i")}]}:{}),...(cat?{category:cat}:{})};res.json(await Product.find(filter).sort({featured:-1,createdAt:-1}))}catch(e){res.status(500).json({message:e.message})}});
app.get("/api/products/:slug",async(req,res)=>{try{await seedDb();const p=await Product.findOne({slug:req.params.slug,active:true});if(!p)return res.status(404).json({message:"Product not found"});res.json(p)}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/auth/register",async(req,res)=>{try{await db();const{name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({message:"Name, valid email and password of 6+ characters required"});if(await User.findOne({email:email.toLowerCase()}))return res.status(409).json({message:"Email already registered"});const u=await User.create({name,email:email.toLowerCase(),passwordHash:await bcrypt.hash(password,12)});res.status(201).json({token:token(u),user:{name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/auth/login",async(req,res)=>{try{await db();const u=await User.findOne({email:String(req.body.email||"").toLowerCase()});if(!u||!(await bcrypt.compare(req.body.password||"",u.passwordHash)))return res.status(401).json({message:"Invalid email or password"});res.json({token:token(u),user:{name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.get("/api/auth/me",auth,async(req,res)=>{await db();const u=await User.findById(req.user.id).select("-passwordHash");res.json(u)});
app.post("/api/coupons/validate",async(req,res)=>{try{await db();const c=await Coupon.findOne({code:String(req.body.code||"").toUpperCase(),active:true});if(!c||c.expiresAt&&c.expiresAt<new Date()||Number(req.body.total||0)<c.minOrder)return res.status(400).json({message:"Invalid or unavailable coupon"});const total=Number(req.body.total);const discount=c.type==="percent"?Math.min(total,total*c.value/100):Math.min(total,c.value);res.json({code:c.code,discount,total:Math.max(0,total-discount)})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/orders",async(req,res)=>{try{await db();const{items,total,paymentMethod="cod",shipping}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({message:"Cart is empty"});const ids=items.map(i=>i.productId);const products=await Product.find({_id:{$in:ids},active:true});if(products.length!==items.length)return res.status(400).json({message:"One or more products are unavailable"});for(const i of items){const p=products.find(x=>x._id.toString()===i.productId);if(!p||i.qty<1||p.stock<i.qty)return res.status(400).json({message:"Insufficient stock for "+(p?.name||"product")})}const order=await Order.create({userId:req.user?.id,items,total,paymentMethod,shipping,paymentStatus:paymentMethod==="cod"?"pending":"created"});for(const i of items)await Product.updateOne({_id:i.productId},{$inc:{stock:-i.qty}});if(shipping?.email)await sendEmail(shipping.email,"Order received — DDCS","<h2>Order received</h2><p>Your order <b>"+order._id+"</b> has been received.</p>");res.status(201).json(order)}catch(e){res.status(500).json({message:e.message})}});
app.get("/api/orders",auth,async(req,res)=>{await db();const filter=req.user.role==="admin"?{}:{userId:req.user.id};res.json(await Order.find(filter).sort({createdAt:-1}))});
app.patch("/api/orders/:id/status",auth,admin,async(req,res)=>{await db();const allowed=["pending","confirmed","processing","shipped","delivered","cancelled"];if(!allowed.includes(req.body.status))return res.status(400).json({message:"Invalid status"});const o=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!o)return res.status(404).json({message:"Order not found"});res.json(o)});
app.post("/api/admin/products",auth,admin,async(req,res)=>{await db();res.status(201).json(await Product.create(req.body))});
app.patch("/api/admin/products/:id",auth,admin,async(req,res)=>{await db();res.json(await Product.findByIdAndUpdate(req.params.id,req.body,{new:true}))});
app.delete("/api/admin/products/:id",auth,admin,async(req,res)=>{await db();await Product.findByIdAndUpdate(req.params.id,{active:false});res.json({success:true})});
app.post("/api/payments/create-order",async(req,res)=>{try{if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.json({demo:true,orderId:"demo_"+Date.now()});const rzp=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});const order=await rzp.orders.create({amount:Math.round(Number(req.body.amount)*100),currency:"INR",receipt:"ddcs_"+Date.now()});res.json({demo:false,keyId:process.env.RAZORPAY_KEY_ID,...order})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/payments/verify",async(req,res)=>{try{const{razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET||"").update(razorpay_order_id+"|"+razorpay_payment_id).digest("hex");if(!razorpay_signature||expected!==razorpay_signature)return res.status(400).json({verified:false});await db();await Order.findOneAndUpdate({paymentOrderId:razorpay_order_id},{paymentStatus:"paid",paymentId:razorpay_payment_id,status:"confirmed"});res.json({verified:true})}catch(e){res.status(500).json({message:e.message})}});
app.post("/api/automation/order-confirmation",async(req,res)=>{try{res.json({channel:"email",...(await sendEmail(req.body.to,"Order confirmation",req.body.html||"Thanks for your order!"))})}catch(e){res.status(500).json({message:e.message})}});
app.get("/api/admin/stats",auth,admin,async(_,res)=>{await db();const[products,orders,customers,agg]=await Promise.all([Product.countDocuments({active:true}),Order.countDocuments(),User.countDocuments({role:"customer"}),Order.aggregate([{$match:{paymentStatus:"paid"}},{$group:{_id:null,revenue:{$sum:"$total"}}}])]);res.json({products,orders,customers,revenue:agg[0]?.revenue||0})});
module.exports=app;